### ISSUE TITLE
Structural subtyping

### ISSUE THREAD

**Issue by Simn** [paulfitz/haxe#1]
This is my test file:

``` java
class Main {
    static function main() {
        var c = new Main();
        c.test2 = 9;
        c.test("foo");
        trace(c.test2);
        var c:{ function test(a:String):Void; var test2:Int; } = c;
        trace(c.test2);
        c.test("bar");

        var d:Dynamic = c;
        trace(d.test2);
        d.test("bar");

        var a = { length: 12, test: function() return "foo" };
        trace(a.length);
        trace(a.test());
    }

    function new() { }

    public var test2:Int;

    public function test(a:String) {
        trace("called " + a + ", " + test2);
    }
}
```

**Comment by paulfitz** [comment]
This test gets at the heart of troubles I've had with anon translation.  Actually, I realize now that not even something as basic as `c.test` translates well (where `c` is an instance of `Main`), since it will get called automatically. The translation of `c.test` needs to use ruby's `Object#method`, and is completely different to the translation of `c.test()`, or if `c.test` is a variable rather than a function. If I could resolve that, the anon translation might be best handled by instead of `OpenStruct` or `Hash`, using something custom that mimics regular instances in just the ways we need. Will look at this some more. Thanks for zooming in on this @Simn.

**Comment by Simn** [comment]
Note that `c.test` becomes `FClosure(Some c, test)`, so this case is easy to detect. Static closures do not have a special field access type, so you have to detect `FStatic` nodes which are not part of the `e` in `TCall(e, el)`.

**Comment by paulfitz** [comment]
@Simn thanks for the `FClosure` tip.  Not sure yet if this is useful but: I took a look at the implementation of `OpenStruct`, and found that it is short and simple, and it is easy to make a variant to give something that behaves more like regular instances. So it would be possible to have code like this:

``` ruby
thing = HxOpenStruct.new
thing.add_one = lambda{|x| x+1}
thing.forty = 40
thing.forty_two = lambda{ 42 }
puts (thing.add_one 10)   # => 11
puts thing.forty          # => 40
puts thing.forty_two      # => 42
puts thing.method(:add_one).call(20) # => 21
```

What I'm trying to get at here is that a translation for a haxe structure could also work if a regular class instance (is that the right term? feels redundant) were substituted in.  However, it assumes that when translating we always know for sure whether the field in question is a function or not, and I'm not at all sure that's the case.

Another option is changing the translation of all methods so that they return lambdas that are then called :-).  Yuck.

Modified OpenStruct here https://gist.github.com/paulfitz/10341879#file-hstruct-rb

**Comment by paulfitz** [comment]
@Simn I finally got some time to poke at the ruby target again. I have something that is working a lot better. I now keep `x.y` as a translation for field accesses on classes only. Once I'm dealing with the Dynamic case or structural subtyping, I switch to `x[:y]` instead. For hashes, this works like `x.y` in other languages, the key being that it doesn't call `y` automatically if it is a method. Regular classes don't have a `[]` operator, but it is easy to add one that works just like hashes. Your test case translates correctly now, here's ruby on the left, javascript on the right:

``` js
   def Main.main                   Main.main = function() {             
      c = Main.new                      var c = new Main();             
      c.test2 = 9                       c.test2 = 9;                    
      c.test("foo")                     c.test("foo");                  
      puts c.test2                      console.log(c.test2);           
      c1 = c                            var c1 = c;                     
      puts c1[:test2]                   console.log(c1.test2);          
      c1[:test].call("bar")             c1.test("bar");                 
      d = c1                            var d = c1;                     
      puts d[:test2]                    console.log(d.test2);           
      d[:test].call("bar")              d.test("bar");                  
      a_length = 12                     var a_length = 12;              
      a_test = lambda {                 var a_test = function() {       
        return "foo"                            return "foo";           
      }                                 };                              
      puts a_length                     console.log(a_length);          
      puts (a_test).call                console.log(a_test());          
    end                             };                                      
```

A sequence like `d[:test].call("bar")` isn't as neat as `d.test("bar")` but it isn't so bad either, that's the code you would need to call a function stored in a hash in ruby `{ test: <function>}`

**Comment by Simn** [comment]
I tried it today and it looks good so far. Good job!
