### ISSUE TITLE
haxe_me breaks selection of sub-Arrays using a Range object

### ISSUE THREAD

**Issue by downslope7** [paulfitz/haxe#4]
The code [here](https://github.com/paulfitz/haxe/blob/ruby5/genrb.ml#L1623-L1627) breaks accessing Ruby arrays with a Range object. The ruby-doc entry for the methods of accessing the elements of an array is [here](http://ruby-doc.org/core-2.2.0/Array.html#class-Array-label-Accessing+Elements). 

Unfortunately this breaks daff for me so I can't update from 1.1.19 (which is broken for me when highlighting a diff that is showing reordered elements).

Stack trace from trying to run `binding.pry` in one of our production apps: 

```
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daff-1.2.6/lib/daff.rb:22:in `method': 0..-1 is not a symbol nor a string (TypeError)
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daff-1.2.6/lib/daff.rb:22:in `block in haxe_me'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:468:in `block in exec_hook'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:467:in `tap'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:467:in `exec_hook'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:81:in `initialize'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `new'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
    from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pry-0.10.1/lib/pry/core_extensions.rb:45:in `pry'
    from rock.rb:127:in `<main>'
```

**Comment by BenGood** [comment]
I am running into the same issue with daff. More specifically, it's not that this breaks daff but bringing daff into another project breaks the project because it runs the haxe_me method linked to above for the base ruby array. haxe_me overrides the [] method for Array unless it's called as Array[Fixnum]. This breaks code elsewhere in the application that use Array[Range] or Array[start, length]. 

I'm not totally sure why Array needs to be 'haxed'. The haxe_me method seems to add [] syntax for accessing attributes but I don't know how that's useful for Array.

**Comment by paulfitz** [comment]
Good point. I'll revert the 'haxing' of Array since it is currently doing more harm than good. Sorry for breakage.

**Comment by paulfitz** [comment]
Reverted for daff gem release 1.3.10, please reopen if problems persist. Thanks!
