### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by fullofcaffeine** [paulfitz/haxe#5]
Hey Paul,

I see you're making some commits to this branch, but there's no status information whatsoever. Are you still using it for your own projects? How is it going? Any chances it could be merged back and become an official Haxe target anytime soon? :)

**Comment by paulfitz** [comment]
This is very much a scratch-my-own-itch thing. I created this fork, and continue to maintain it, for daff https://github.com/paulfitz/daff.  It supports a subset of haxe features, but is by no means complete.  I stopped once I had everything I personally needed, and adding any more was going to require an uglier translation (or monkey patching).

I can't myself justify the time to push this through to completion and get it merged upstream.  Wish I could, it is fun to hack on.

**Comment by fullofcaffeine** [comment]
K, thanks for the update!

**Comment by fullofcaffeine** [comment]
@paulfitz Could you give a brief description of the current state and what's lacking? Some hints on what direction tot take, challenges and where to look would suffice, and I'd take it from there.

I'd like to take a peek and try to further develop the target. I totally understand you don't have the time to work on it (and I thank you for open-sourcing it in the first place!) but It'd be neat to have a Ruby target for Haxe and it's a pity that you already put all this effort into it, the gist is available and in a working state, but not being further developed by someone from the Haxe community yet (being in its best interest to do so!).

Thanks in advance!

**Comment by fullofcaffeine** [comment]
Ping :)

**Comment by paulfitz** [comment]
The main material is https://github.com/paulfitz/haxe/blob/ruby5/genrb.ml.  I started from one of the other gen*.ml files, and adapted it.  There's not actually a lot to it, the biggest obstacle for me was learning ocaml.  I never did figure out how to debug effectively in that language, which was a real pain. Ruby turns out to be, for haxe purposes, quite like php. The python backend was also interesting to study when it showed up.

The main thing that I didn't figure out how to deal with well were the corner cases, like using a negative index on an array.  I could deal with them by brute force, with ugly non-idiomatic translations, but I wasn't really excited by the result.  Probably there's a way to do basic inference on simple cases and translate them idiomatically, but it was above my ocaml level.

**Comment by fullofcaffeine** [comment]
@paulfitz I didn't see this message before. Thanks for elaborating!

I still have an itch about a Ruby target for Haxe mainly because Ruby is my language of choice for most of the productive stuff I do, and at this point, it's more about the eco-system than about the syntax. I actually kind of prefer Haxe's syntax more in some ways. 

If I could mix-and-match and use  Haxe for some or all of my projects, by leveraging Rails, but not needing to write [a lot of] Ruby + with the advantage of adding a typed layer to it, it'd be so awesome. I acknowledge that it wouldn't be simple though, so it remains in my "someday/maybe" list.
